#!/usr/bin/perl
# recalibrate PrefVote blackbox test baseline data by running the reference implementation (Perl)
use Modern::Perl qw(2024);
use utf8;
use Carp qw(croak);
use Readonly;
use FindBin qw($Bin);
use File::Basename qw(dirname);
use File::Copy qw(cp);;
use YAML::XS qw(Load LoadFile);
use YAML::Dumper;
use IPC::Run qw(run);

# constants
#Readonly::Array my @methods => qw(Core STV Schulze RankedPairs KR2);
Readonly::Scalar my $progname => $0;
Readonly::Scalar my $pvroot => dirname($Bin);
Readonly::Scalar my $count_script => "$pvroot/lab/perl/prefvote/bin/vote-count";

# dump YAML file
# use YAML::Dumper so we can force more compact inline series mode (flow sequences) on lists up to 16 items
sub dump_yaml_file
{
    my ( $filename, @content ) = @_;

    # write to YAML file 3 document sections: parameters, candidate coordinates, voter coordinates
    open my $yaml_fh, ">", $filename
        or croak "failed to write $filename: $!";
    my $dumper = YAML::Dumper->new;
    $dumper->inline_series(16);
    print $yaml_fh $dumper->dump( @content );
    close $yaml_fh
        or croak "failed to close $filename: $!";
    return;
}

# collect run data for all voting methods
sub collect_rundata
{
    my ( $path, $methods ) = @_;
    my %rundata;

    # loop through voting methods - run vote counting with and without ACR tiebreaking
    foreach my $method (@$methods) {
        #say STDERR "collect_rundata - $method";
        my $yaml_text;
        my @cmd = ($count_script, "--format=yaml", "--method=$method", $path);
        run \@cmd, \undef, \$yaml_text;
        my @raw_rundata = Load($yaml_text);
        if (not exists $raw_rundata[0]{$method}) {
            croak "malformed YAML output from $path: $method voting result not found";
        }
        $rundata{$method} = $raw_rundata[0]{$method};
    }
    return \%rundata;
}

# handle recalibration of each file
sub process_file
{
    my $path = shift;

    # verify $path exists and is a file
    if (not -e $path) {
        croak "$progname: file $path does not exist";
    }
    if (not -f $path) {
        croak "$progname: $path is not a file";
    }

    # read YAML data from file
    # @yaml_doc is a list containing 3 YAML documents: 0=vote metadata, 1=ballots, 2=optional blackbox test data
    my @yaml_doc = LoadFile($path);
    if (not scalar @yaml_doc) {
        croak "$progname: failed to parse YAML from $path";
    }

    # make backup copy of file
    my $backup_file = $path.".bak";
    cp($path, $backup_file)
        or croak "$progname: failed to back up $path: $!";

    # get voting methods declared by the test file
    my @methods = split " ", $yaml_doc[0]->{method};
    #say STDERR "process_file($path): methods = ".join(" - ", @methods );

    # construct and replace new blackbox testing data
    $yaml_doc[2] = collect_rundata($path, \@methods);
    say STDERR "updating $path";
    dump_yaml_file($path, @yaml_doc);
    return;
}

# process command line
my @files = @ARGV;

foreach my $path (@files) {
    process_file($path);
}
